version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  db:
    image: mariadb:latest
    restart: always
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_DATABASE=main
      - MARIADB_USER=sci
      - MARIADB_PASSWORD=mypassword
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=main
      - MARIADB_USER=sci
      - MARIADB_PASSWORD=mypassword
      - DATABASE_URL=mysql://sci:mypassword@db:3306/main
      - NODE_ENV=development
    depends_on:
      - redis
      - db
    volumes:
      - ./:/app

  frontend-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=main
      - MARIADB_USER=sci
      - MARIADB_PASSWORD=mypassword
      - DATABASE_URL=mysql://sci:mypassword@db:3306/main
      - NODE_ENV=production
    depends_on:
      - redis
      - db
volumes:
  db_data:
  redis_data: