"use client"

import styled from "styled-components";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import { useEffect, useState } from "react";
import CurrentActiveProvider from "@/app/components/doc/provider";

const Holder = styled.div`
    margin-left: auto;
    margin-right: auto;
    width: var(--cont-width);
    display: flex;
    min-height: 100vh;
`


export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [currentActive, setCurrentActive] = useState('');

    useEffect(() => {
        let titleList: Array<Element> = []
        document.querySelectorAll("[data-type='md-title']").forEach(elem => titleList.push(elem))
        const listenForScroll = () => {
            try{
                let min: Element = titleList[0]
                titleList.forEach((item) => {
                    if (Math.abs(item.getBoundingClientRect().top) <= Math.abs(min.getBoundingClientRect().top)) {
                        min = item
                    }
                });
                setCurrentActive(min.id);
            }catch(e){}
        };
        document.addEventListener('hashchange', listenForScroll);
        document.addEventListener("scroll", listenForScroll)
        listenForScroll()
        return () => {
            document.removeEventListener("scroll", listenForScroll)
            document.removeEventListener('hashchange', listenForScroll);
        }
    }, [])
    return (
        <>
            <CurrentActiveProvider value={currentActive}>
                <Holder >{children}</Holder>
            </CurrentActiveProvider>
        </>
    );
}
