
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import StyledComponentsRegistry from './lib/registry'
import { headers } from 'next/headers'
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let ip = headers().get("x-forwarded-for")
  return (
    <>
    <html lang="en">
      <body>
      <NextTopLoader showSpinner={false} color="#7d7d7d"/>
        <StyledComponentsRegistry>
          <Header userIp={ip!}></Header>
          {children}
          <Footer></Footer>
        </StyledComponentsRegistry>
      </body>
    </html>
    </>
  );
}
