name: deploy
on:
  push:
    branches: ['main']
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy using ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PK }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/opc/sci-wiki
          rm -rf .env
          touch .env
          echo JWT_KEY="${{secrets.JWT_KEY}}" >> .env
          echo TURNSTILE_KEY="${{secrets.TURNSTILE_KEY}}" >> .env
          echo RESEND_KEY="${{secrets.RESEND_KEY}}" >> .env
          echo R2_ACCESS="${{secrets.R2_ACCESS}}" >> .env
          echo R2_ACCESS_PRIVATE="${{secrets.R2_ACCESS_PRIVATE}}" >> .env
          echo R2_ACC="${{secrets.R2_ACC}}" >> .env
          
          git pull https://${{ secrets.GH_SECRET }}@github.com/gshs-sci/sci-wiki/
          docker compose --profile prod up --build -d
