name: deploy
on:
  push:
    branches: ['main']
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy using ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PK }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/opc/sci-wiki
          git pull https://${{ secrets.GH_SECRET }}@github.com/gshs-sci/sci-wiki/
          docker compose --profile prod down
          docker compose --profile prod up --build
